### ISSUE TITLE
Must-haves & should-haves

### ISSUE THREAD

**Issue by MattIPv4** [botblock/discord-botlist-best-practices#1]
I think it’s be great if we split this into two separate files (or sections).

The first should contain what we consider the must-haves to be a bot list. This is most of the current content.

A second section can then be created which we can put best practice suggestions in that are should-haves for bot lists.

**Comment by Andre601** [comment]
Also maybe a third section of what you can have but isn't needed?
Or maybe even a part about what a bot list should NOT have or do...

**Comment by MattIPv4** [comment]
@Andre601 That’s exactly what the should-haves are... things a list should have but not must have.

I don’t think creating a list of negatives is a good idea.
