### ISSUE TITLE
Clarify point 1 (TLD)

### ISSUE THREAD

**Issue by MattIPv4** [botblock/discord-botlist-best-practices#5]
I think that we should update point 1 to be more class in the expectations of a bot list domain.

In my view it should reach the following:
 - Uses it’s own custom domain
 - Uses a respectable and paid TLD

I believe we should avoid listing non-respectable TLDs such as tk as this could potentially act as a defends if we do not list one and a user cites that.

This should be able to be formed into a single sentence for the bullet point, such as `must use a custom domain name with a respectable and paid TLD`.

**Comment by MattIPv4** [comment]
Thoughts and ideas are welcome in this before we make the change.

**Comment by Andre601** [comment]
I made a Draft PR ( #6 ) to discuss it there and make changes quickly and easier.
